// <auto-generated />
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", t =>
                        {
                            t.HasCheckConstraint("CK_Email", "[Email] LIKE '%@%.%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jeremy.bazin@email.com",
                            Password = "Test123=",
                            Pseudo = "rains-",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.martin@email.com",
                            Password = "5Gh#zBvKw3PxYrE",
                            Pseudo = "MidnightWolf",
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie.nguyen@email.com",
                            Password = "fT7#eRm2QxLz9Dy$",
                            Pseudo = "GalacticNinja",
                            Role = "user"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david.lee@email.com",
                            Password = "V6b$UwPcNz @hM8xK",
                            Pseudo = "DragonSlayer",
                            Role = "user"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emma.garcia@email.com",
                            Password = "aH5%kXjL9$qBm2W",
                            Pseudo = "PixelPrincess",
                            Role = "user"
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank.chen@email.com",
                            Password = "qJ9@fM8cWu5$xLrE",
                            Pseudo = "PhantomGamer",
                            Role = "user"
                        },
                        new
                        {
                            Id = 7,
                            Email = "grace.wong@email.com",
                            Password = "7Km&zRb#vGy2hNj",
                            Pseudo = "ElectricNoodle",
                            Role = "user"
                        },
                        new
                        {
                            Id = 8,
                            Email = "henry.zhang@email.com",
                            Password = "T4c#nSv@wGj2RkF",
                            Pseudo = "MoonlightRider",
                            Role = "user"
                        },
                        new
                        {
                            Id = 9,
                            Email = "isabella.lopez@email.com",
                            Password = "H8f$kL3q#sVp9Xy",
                            Pseudo = "GoldenPhoenix",
                            Role = "user"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jack.kim@email.com",
                            Password = "3ZgY*6tLx#pVfDhN",
                            Pseudo = "StormChaser",
                            Role = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
